spring:
  application:
    name: registry-service

server:
  port: 7001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:7001/eureka